{ inputs, ... }:
{
  imports = [ inputs.treefmt-nix.flakeModule ];

  perSystem = { ... }: {
    treefmt = {
      projectRootFile = "flake.nix";

      programs.nixfmt.enable = true;
      programs.mdformat.enable = true;

      # Haskell formatting (Haskell source and *.cabal files)
      programs.fourmolu.enable = true; # respects fourmolu.yaml
      programs.cabal-gild.enable = true;

      settings.global.excludes = [
        # Golden test files (changing them breaks tests)
        "test/golden/**"
        # Generated by cabal2nix
        "Blindhuhn.nix"
      ];
    };
  };
}
