{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

-- | Injects client-side search UI into HTML generated by Agda's HTML backend.
--
-- The UI's source files (JS, CSS) live under @data\/search@ and are embedded
-- into the binary at compile time.  Some runtime dependencies need to be
-- vendored (they are not commited to the repository). @Blindhuhn.Search.Embed@
-- locates those assets via the @$BLINDHUHN_VENDORED_ASSETS_DIR$@ environment
-- variable.
module Blindhuhn.Search (
  findPreviousInjections,
  hasPreviousInjection,
  hashIndex,
  inject,
  injectHead,
)
where

import Agda.Syntax.Common.Pretty
import Agda.TypeChecking.Monad.Base (MonadTCM)
import Agda.TypeChecking.Monad.Debug (MonadDebug)
import Control.Monad (filterM, forM_)
import Control.Monad.IO.Class (MonadIO (..))
import Data.ByteString (ByteString)
import Data.FileEmbed (embedDir)
import Data.Text (Text)
import Numeric (showHex)
import System.Directory (listDirectory)
import System.FilePath (takeExtension, (</>))

import Data.ByteString qualified as BS
import Data.Hashable qualified as Hashable
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextEncoding
import Data.Text.Lazy qualified as L

import Blindhuhn.Search.Embed (embedVendoredAsset)

import Blindhuhn.Log qualified as Log

-- | The search UI assets (JS, CSS).
searchAssets :: [(FilePath, ByteString)]
searchAssets = $(embedDir "data/search")

-- | Vendored dependencies (e.g. JS libraries).
--
-- For now, this is only the library used to implement fuzzy
-- matching of search results (`fzf`).
vendoredAssets :: [(FilePath, ByteString)]
vendoredAssets =
  [ ("fzf.es.js", $(embedVendoredAsset "fzf/dist/fzf.es.js"))
  , ("fzf-LICENSE.txt", $(embedVendoredAsset "fzf/license.txt"))
  ]

-- | All search UI assets.
--
-- Copied into the output directory at the given relative path.
assets :: [(FilePath, ByteString)]
assets =
  concat
    [ searchAssets
    , vendoredAssets
    ]

headSnippet :: Text -> Text
headSnippet hash' =
  Text.concat
    [ "<!--blindhuhn-search-->"
    , "<meta name=\"blindhuhn-index-hash\" content=\""
    , hash'
    , "\">"
    , "<link rel=\"icon\" href=\"/favicon.svg\" sizes=\"any\">"
    , "<link rel=\"stylesheet\" href=\"blindhuhn-search.css\">"
    , "<script type=\"module\" src=\"blindhuhn-search.js\"></script>"
    , "<!--/blindhuhn-search-->"
    ]

-- | Insert the search UI's @\<meta\>@\/@\<link\>@\/@\<script\>@ tags right
-- before the first @\<\/head\>@.
--
-- A no-op if there is no @\<\/head\>@ to inject into. Does /not/ check
-- whether @html@ already carries a previous injection.
injectHead :: Text -> Text -> Text
injectHead hash html =
  case Text.breakOn "</head>" html of
    (before, after)
      | not (Text.null after) -> before <> headSnippet hash <> after
    (cleaned, _) -> cleaned

-- | Get the path to all @*.html@ files in @outputDir@.
--
-- The paths are prefixed with @outputDir@.
htmlFiles :: MonadIO m => FilePath -> m [FilePath]
htmlFiles outputDir = do
  files <- filter ((== ".html") . takeExtension) <$> liftIO (listDirectory outputDir)
  pure $ map (outputDir </>) files

-- Has a page with this content already had the search UI injected into it?
hasPreviousInjection :: Text -> Bool
hasPreviousInjection content = "<meta name=\"blindhuhn-index-hash\"" `Text.isInfixOf` content

-- | List @*.html@ files in @outputDir@ that already carry a previous injection.
findPreviousInjections :: MonadIO m => FilePath -> m [FilePath]
findPreviousInjections outputDir =
  htmlFiles outputDir >>= filterM (fmap hasPreviousInjection . readFileText)
 where
  readFileText path = TextEncoding.decodeUtf8 <$> liftIO (BS.readFile path)

-- | Derive a (non-cryptographic) hash from the serialized index.
-- Used to prevent the search UI from accidentally serving stale results.
hashIndex :: L.Text -> Text
hashIndex content = Text.pack $ showHex (fromIntegral (Hashable.hash content) :: Word) ""

-- | Inject search UI into HTML files in @outputDir@.
--
-- Writes the search assets into @outputDir@ and inject them into every @*.html@ file already present there.
--
-- Assumes none of the @*.html@ files in @outputDir@ already carry a previous injection.
-- Use @findPreviousInjections@ to prevent double-injection.
--
-- The injection is keyed by @hash@, which should be derived from the search index using @hashIndex@.
-- This ensure that the injected UI never loads a stale search index.
inject :: (MonadTCM m, MonadDebug m) => FilePath -> Text -> m ()
inject outputDir hash = do
  forM_ assets $ \(name, contents) -> do
    let outputPath = (outputDir </> name)
    Log.info "blindhuhn.search" $ "Writing asset" <+> parens (pretty name)
    liftIO $ BS.writeFile outputPath contents
    Log.debug "blindhuhn.search" $ "Wrote asset to" <+> pretty outputPath

  htmlFiles outputDir >>= mapM_ \path -> do
    Log.info "blindhuhn.search" $ "Injecting search UI" <+> parens (pretty path)
    liftIO $ modifyFile path $ injectHead hash
 where
  modifyFile :: FilePath -> (Text -> Text) -> IO ()
  modifyFile path f = do
    contents <- TextEncoding.decodeUtf8 <$> BS.readFile path
    BS.writeFile path (TextEncoding.encodeUtf8 (f contents))
